unit uPSI_API_cURL;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 

 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_API_cURL = class(TPSPlugin)
  public
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TAPI_cURL(CL: TPSPascalCompiler);
procedure SIRegister_API_cURL(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TAPI_cURL(CL: TPSRuntimeClassImporter);
procedure RIRegister_API_cURL(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   APIBase
  ,API_Output
  ,API_cURL
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_API_cURL]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TAPI_cURL(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TAPIBase', 'TAPI_cURL') do
  with CL.AddClassN(CL.FindClass('TAPIBase'),'TAPI_cURL') do
  begin
    RegisterMethod('Constructor Create( aAPI_Output : tAPI_Output)');
    RegisterMethod('Function test : string');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_API_cURL(CL: TPSPascalCompiler);
begin
  SIRegister_TAPI_cURL(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_TAPI_cURL(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TAPI_cURL) do
  begin
    RegisterConstructor(@TAPI_cURL.Create, 'Create');
    RegisterMethod(@TAPI_cURL.test, 'test');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_API_cURL(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TAPI_cURL(CL);
end;

 
 
{ TPSImport_API_cURL }
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_cURL.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_API_cURL(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_cURL.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_API_cURL(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
