unit uPSI_API_IniFile;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 

 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_API_IniFile = class(TPSPlugin)
  public
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TAPI_IniFile(CL: TPSPascalCompiler);
procedure SIRegister_TIniFile(CL: TPSPascalCompiler);
procedure SIRegister_API_IniFile(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TAPI_IniFile(CL: TPSRuntimeClassImporter);
procedure RIRegister_TIniFile(CL: TPSRuntimeClassImporter);
procedure RIRegister_API_IniFile(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   APIBase
  ,Registry
  ,MessagesLog
  ,API_IniFile
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_API_IniFile]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TAPI_IniFile(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TAPIBase', 'TAPI_IniFile') do
  with CL.AddClassN(CL.FindClass('TAPIBase'),'TAPI_IniFile') do
  begin
    RegisterMethod('Function OpenIniFile( aFilename : String) : TIniFile');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_TIniFile(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TPersistent', 'TIniFile') do
  with CL.AddClassN(CL.FindClass('TPersistent'),'TIniFile') do
  begin
    RegisterMethod('Constructor Create( aFilename : String; aMessagesLog : tMessagesLog)');
    RegisterMethod('Procedure WriteString( const aSection : string; const aKey : String; const aValue : String)');
    RegisterMethod('Function ReadString( const aSection : string; const aKey : String; const aDefault : string) : String');
    RegisterMethod('Function DeleteSection( const aSection : string) : Boolean');
    RegisterMethod('Function DeleteKey( const aSection : string; const aKey : string) : boolean');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_API_IniFile(CL: TPSPascalCompiler);
begin
  SIRegister_TIniFile(CL);
  SIRegister_TAPI_IniFile(CL);
 CL.AddConstantN('API_IniFile_cannot_find_filename','String').SetString( 'Cannot find filename [%s]');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_TAPI_IniFile(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TAPI_IniFile) do
  begin
    RegisterMethod(@TAPI_IniFile.OpenIniFile, 'OpenIniFile');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_TIniFile(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TIniFile) do
  begin
    RegisterConstructor(@TIniFile.Create, 'Create');
    RegisterMethod(@TIniFile.WriteString, 'WriteString');
    RegisterMethod(@TIniFile.ReadString, 'ReadString');
    RegisterMethod(@TIniFile.DeleteSection, 'DeleteSection');
    RegisterMethod(@TIniFile.DeleteKey, 'DeleteKey');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_API_IniFile(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TIniFile(CL);
  RIRegister_TAPI_IniFile(CL);
end;

 
 
{ TPSImport_API_IniFile }
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_IniFile.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_API_IniFile(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_IniFile.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_API_IniFile(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
