unit uPSI_API_Zip;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 

 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_API_Zip = class(TPSPlugin)
  public
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TAPI_Zip(CL: TPSPascalCompiler);
procedure SIRegister_API_Zip(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TAPI_Zip(CL: TPSRuntimeClassImporter);
procedure RIRegister_API_Zip(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   Zip
  ,APIBase
  ,API_Zip
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_API_Zip]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TAPI_Zip(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TAPIBase', 'TAPI_Zip') do
  with CL.AddClassN(CL.FindClass('TAPIBase'),'TAPI_Zip') do
  begin
    RegisterMethod('Function ZipCompress : Boolean');
    RegisterMethod('Function ZipExtractAll : Boolean');
    RegisterMethod('Function ZipExtractFile( const aZipFilename : String; const aFileName : string; const aPath : string; aCreateSubdirs : Boolean) : Boolean');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_API_Zip(CL: TPSPascalCompiler);
begin
  SIRegister_TAPI_Zip(CL);
 CL.AddConstantN('API_Zip_NotFileExists','String').SetString( 'ZipFilename cannot be found [%s]');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_TAPI_Zip(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TAPI_Zip) do
  begin
    RegisterMethod(@TAPI_Zip.ZipCompress, 'ZipCompress');
    RegisterMethod(@TAPI_Zip.ZipExtractAll, 'ZipExtractAll');
    RegisterMethod(@TAPI_Zip.ZipExtractFile, 'ZipExtractFile');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_API_Zip(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TAPI_Zip(CL);
end;

 
 
{ TPSImport_API_Zip }
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_Zip.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_API_Zip(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_Zip.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_API_Zip(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
