unit uPSI_API_RESTClient;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 

 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_API_RESTClient = class(TPSPlugin)
  public
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TAPI_RESTClient(CL: TPSPascalCompiler);
procedure SIRegister_API_RESTClient(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TAPI_RESTClient(CL: TPSRuntimeClassImporter);
procedure RIRegister_API_RESTClient(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   APIBase
  ,API_Output
  ,API_RESTClient
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_API_RESTClient]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TAPI_RESTClient(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TAPIBase', 'TAPI_RESTClient') do
  with CL.AddClassN(CL.FindClass('TAPIBase'),'TAPI_RESTClient') do
  begin
    RegisterMethod('Constructor Create( aAPI_Output : tAPI_Output)');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_API_RESTClient(CL: TPSPascalCompiler);
begin
  SIRegister_TAPI_RESTClient(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_TAPI_RESTClient(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TAPI_RESTClient) do
  begin
    RegisterConstructor(@TAPI_RESTClient.Create, 'Create');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_API_RESTClient(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TAPI_RESTClient(CL);
end;

 
 
{ TPSImport_API_RESTClient }
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_RESTClient.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_API_RESTClient(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_RESTClient.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_API_RESTClient(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
