unit uPSI_API_Exec;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 

 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_API_Exec = class(TPSPlugin)
  public
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TAPI_Exec(CL: TPSPascalCompiler);
procedure SIRegister_API_Exec(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TAPI_Exec(CL: TPSRuntimeClassImporter);
procedure RIRegister_API_Exec(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   APIBase
  ,API_Exec
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_API_Exec]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TAPI_Exec(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TAPIBase', 'TAPI_Exec') do
  with CL.AddClassN(CL.FindClass('TAPIBase'),'TAPI_Exec') do
  begin
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_API_Exec(CL: TPSPascalCompiler);
begin
  SIRegister_TAPI_Exec(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_TAPI_Exec(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TAPI_Exec) do
  begin
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_API_Exec(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TAPI_Exec(CL);
end;

 
 
{ TPSImport_API_Exec }
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_Exec.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_API_Exec(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_API_Exec.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_API_Exec(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
