







(* Delphi 10 Seattle / C++Builder Seattle *)
{$IFDEF VER300}
  ($DEFINE DELPHI10}
{$ENDIF}

(* Delphi XE8 / C++Builder XE8 *)
{$IFDEF VER290}
  {$DEFINE DELPHIXE8}
{$ENDIF}

(* Delphi XE7 / C++Builder XE7 *)
{$IFDEF VER280}
  {$DEFINE DELPHIXE7}
{$ENDIF}

(* Delphi XE6 / C++Builder XE6 *)
{$IFDEF VER270}
  {$DEFINE DELPHIXE6}
{$ENDIF}

(* Delphi XE5 / C++Builder XE5 *)
{$IFDEF VER260}
  {$DEFINE DELPHIXE5}
{$ENDIF}

(* Delphi XE4 / C++Builder XE4 *)
{$IFDEF VER250}
  {$DEFINE DELPHIXE4}
{$ENDIF}

(* Delphi XE3 / C++Builder XE3 *)
{$IFDEF VER240}
  {$DEFINE DELPHIXE3}
{$ENDIF}

(* Delphi XE2 / C++Builder XE2 *)
{$IFDEF VER230}
  {$DEFINE DELPHIXE2}
{$ENDIF}

(* Delphi XE / C++Builder XE (Win32) *)
{$IFDEF VER220}
   {$DEFINE DELPHIXE}
{$ENDIF}

(* Delphi 2010 / C++Builder 2010 (Win32) *)
{$IFDEF VER210}
   {$DEFINE DELPHI2010}
{$ENDIF}

(* Delphi 2009 / C++Builder 2009 (Win32) *)
{$IFDEF VER200}
   {$DEFINE DELPHI2009}
{$ENDIF}

